server:
  port: 8080
  servlet:
    context-path: /demo

sms:
  aliyun:
    accessKeyId: your-access-key-id
    accessKeySecret:  your-access-key-secret
    signName: your-sign-name
    endpoint: dysmsapi.aliyuncs.com
    templateCode: SMS_#########
    # 是否开启短信服务
    pushSms: true

alipay:
  appId: your-appId
  privateKey: your-privateKey
  publicKey: your-publicKey
  format: json
  charset: UTF-8
  signType: RSA2
  gatewayUrl: https://openapi.alipay.com/gateway.do

