spring:
  data:
    elasticsearch:
      client:
        rest:
          uris: http://localhost:9200
          username: elastic
          password: your-password
      repositories:
        enabled: true

